export const ROOT_CONTEXT_TRUE = Symbol.for("__TRUE")
export const ROOT_CONTEXT_FALSE = Symbol.for("__FALSE")
export const GET_WITH_NEW_ROOT = Symbol.for("__GET_WITH_NEW_ROOT")
export const PROXY_CONTEXT = Symbol.for("__PROXY_CONTEXT")
export const RAW_VALUE = Symbol.for("__RAW_VALUE")
export const GET_RAW_PROPERTY = Symbol.for("__GET_RAW_PROPERTY")
export const COST = Symbol.for("__CALCULATE_COST")
export const CALCULATE_COST = Symbol.for("__CALCULATE_COST")
