export const TRUE = Symbol.for("$$TRUE")
export const FALSE = Symbol.for("$$FALSE")
export const GET_WITH_NEW_ROOT = Symbol.for("$$GET_WITH_NEW_ROOT")
export const PROXY_CONTEXT = Symbol.for("$$PROXY_CONTEXT")
export const RAW_VALUE = Symbol.for("$$RAW_VALUE")
export const COST = Symbol.for("$$COST")
export const ROUTE = Symbol.for("$$ROUTE")